# Site settings
title: Burgerlijst
email: onthaal@burgerlijst.be
description: > # this means to ignore newlines until "baseurl:"
   Transparantie en participatie voor elke burger
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.burgerlijst.be" # the base hostname & protocol for your site
twitter_username: burgerlijst
facebook_username: burgerlijst
future: true # Otherwise Jekyll will ignore 'future' events... :-/

# Build settings
markdown: kramdown

plugins:
   - bootstrap
   - autoprefixer-rails
   - jekyll-coffeescript
   - jekyll-assets
   - jekyll-pug

sass:
   sass_dir: assets/css

collections:
   events:
      output: true
      permalink: /:collection/:name:output_ext
   kandidaten:
      output: true
      permalink: /kandidaat/:name:output_ext

defaults:
   - scope:
      path: ""
      type: events
     values:
      layout: event
   - scope:
      path: ""
      type: kandidaten
     values:
      layout: kandidaat
   - scope:
      path: "materiaal/social"
     values:
      materiaal: true
      social: true
   - scope:
      path: "materiaal/logo-met-tagline"
     values:
      materiaal: true
      logo: true
      tagline: true
   - scope:
      path: "materiaal/logo-zonder-tagline"
     values:
      materiaal: true
      logo: true
      tagline: false

